name:                aula15-servant
version:             0.1.0.0
github:              "githubuser/aula15-servant"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aula15-servant#readme>

dependencies:
- base >= 4.7 && < 5
- servant
- aeson
- servant-server
- wai
- wai-cors
- warp


library:
  source-dirs: src

executables:
  aula15-servant-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aula15-servant
  first-version:
    main:                FirstVersion.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is FirstVersion
    dependencies:
    - aula15-servant

tests:
  aula15-servant-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aula15-servant
